const system = {
    "data":[
        {
            "id":14,
            "type":28,
            "title":"“直播经济时代”加速到来，专场市场如何“危”中抓“机”？",
            "click":64,
            "link":null,
            "recommend":0,
            "photos":null,
            "cover":0,
            "status":true,
            "sort":1,
            "cvoer_path":"",
            "created_timestamp":false,
            "updated_timestamp":false,
            "type_info":{
                "id":28,
                "name":"制度建设",
                "type":"information",
                "value":"1"
            },
            "cover_info":null
        },
        {
            "id":112,
            "type":28,
            "title":"五化宣传",
            "click":17,
            "link":null,
            "recommend":0,
            "photos":null,
            "cover":null,
            "status":true,
            "sort":1,
            "cvoer_path":"",
            "created_timestamp":false,
            "updated_timestamp":false,
            "type_info":{
                "id":28,
                "name":"制度建设",
                "type":"information",
                "value":"1"
            },
            "cover_info":null
        }
    ],
    "links":{
        "first":"http://47.110.135.173/maofancity/admin/public//home/information?page=1",
        "last":"http://47.110.135.173/maofancity/admin/public//home/information?page=1",
        "prev":null,
        "next":null
    },
    "meta":{
        "current_page":1,
        "from":1,
        "last_page":1,
        "path":"http://47.110.135.173/maofancity/admin/public//home/information",
        "per_page":"6",
        "to":2,
        "total":2
    }
}

const complaint = {
    "data":[
        {
            "id":113,
            "type":32,
            "title":"消费纠纷调解制度",
            "click":12,
            "link":null,
            "recommend":0,
            "photos":null,
            "cover":null,
            "status":true,
            "sort":1,
            "cvoer_path":"",
            "created_timestamp":false,
            "updated_timestamp":false,
            "type_info":{
                "id":32,
                "name":"消费投诉处理",
                "type":"information",
                "value":"5"
            },
            "cover_info":null
        }
    ],
    "links":{
        "first":"http://47.110.135.173/maofancity/admin/public//home/information?page=1",
        "last":"http://47.110.135.173/maofancity/admin/public//home/information?page=1",
        "prev":null,
        "next":null
    },
    "meta":{
        "current_page":1,
        "from":1,
        "last_page":1,
        "path":"http://47.110.135.173/maofancity/admin/public//home/information",
        "per_page":"6",
        "to":1,
        "total":1
    }
}
const data = {
    system,
    complaint,
}
export default data