const floor1 = {
    data: [
        { name: 'Design 设计感', numbers: '100--1' },
        { name: '费尼兰思', numbers: '100--2' },
        { name: '片', numbers: '100-A' },
        { name: 'C位', numbers: '100-B' },
        { name: '迪米凯莱', numbers: '101' },
        { name: '馨蒂娅', numbers: '102' },
        { name: '艾慕欧', numbers: '103' },
        { name: '佳德妃', numbers: '105A' },
        { name: '和润', numbers: '105B' },
        { name: '欧谜', numbers: '106' },
        { name: '太古名店', numbers: '107' },
        { name: '胡同', numbers: '108' },
        { name: '爱时妮', numbers: '109' },
        { name: '牡丹公主', numbers: '110' },
        { name: '汤尼', numbers: '110B' },
        { name: '言库', numbers: '111' },
        { name: '1991', numbers: '112' },
        { name: '普古达', numbers: '113' },
        { name: 'CK潮裤', numbers: '115' },
        { name: '懿兰', numbers: '116' },
        { name: '艺潇', numbers: '117A' },
        { name: '井春', numbers: '117B' },
        { name: '313', numbers: '118A' },
        { name: '赛迈', numbers: '118B' },
        { name: '多米Domi', numbers: '119' },
        { name: '黛微微', numbers: '120' },
        { name: '芭利玛.瑞妮', numbers: '121' },
        { name: '衣米来', numbers: '122' },
        { name: 'AL’ombre', numbers: '123' },
        { name: 'VCC', numbers: '125' },
        { name: 'JCM集承美', numbers: '126' },
        { name: '告白季', numbers: '127A' },
        { name: '驰媞', numbers: '127B' },
        { name: '禧宝鹿王', numbers: '128' },
        { name: '赛格', numbers: '129' },
        { name: '漫.美', numbers: '130' },
        { name: '他她迷', numbers: '131A' },
        { name: '慕初', numbers: '131B' },
        { name: 'M-1', numbers: '132' },
        { name: 'm+麦加', numbers: '133' },
        { name: '俞氏名门', numbers: '135' },
        { name: '迪士奈儿', numbers: '136A' },
        { name: 'SLN', numbers: '136B' },
        { name: '赞姿', numbers: '137' },
        { name: '红社女裤', numbers: '138A/138B/139' }
      ]
}
const floor2 = {
    data: [
        { name: 'Za原创工厂店', numbers: '201' },
        { name: 'CC ', numbers: '202' },
        { name: '简沐雅', numbers: '203A' },
        { name: '1989', numbers: '203B' },
        { name: '悦悦家', numbers: '205' },
        { name: '花姐家', numbers: '206' },
        { name: '大里DL', numbers: '206' },
        { name: '名门淑媛', numbers: '207' },
        { name: '1n', numbers: '208A' },
        { name: '欧颜笛', numbers: '208B' },
        { name: '影悦', numbers: '209' },
        { name: 'C.Q.K', numbers: '210A' },
        { name: '法倍儿', numbers: '210B' },
        { name: '琪', numbers: '211A' },
        { name: '依菲亚', numbers: '211B' },
        { name: '木衣家', numbers: '212A' },
        { name: 'HY', numbers: '212B' },
        { name: '喜装', numbers: '213' },
        { name: '欧绮', numbers: '215A' },
        { name: '读雅', numbers: '215B' },
        { name: '依仕维', numbers: '216A' },
        { name: '依仁弗', numbers: '216B' },
        { name: 'CLC', numbers: '217A' },
        { name: '红门', numbers: '217B' },
        { name: '浅庄', numbers: '218A' },
        { name: '圣宝纳', numbers: '218B' },
        { name: '圣玛歌第', numbers: '219A' },
        { name: '兴概念', numbers: '219B' },
        { name: '慕鑫然', numbers: '220-A' },
        { name: '憨厚熊', numbers: '220-B' },
        { name: '简兮', numbers: '221-A' },
        { name: '地铁站', numbers: '221-B' },
        { name: 'Miss Jiang', numbers: '222A' },
        { name: '木棉', numbers: '222B' },
        { name: '宝歌丽娅', numbers: '223' },
        { name: '浅驰', numbers: '225' },
        { name: '后尔', numbers: '226A' },
        { name: '百格姿羽', numbers: '226B' },
        { name: 'Xu+', numbers: '227A' },
        { name: 'nice+', numbers: '227B' },
        { name: '欣盟', numbers: '228A' },
        { name: '知尚', numbers: '228B' },
        { name: '简尚秋', numbers: '229A' },
        { name: '设格', numbers: '229B' },
        { name: '欧衣贝', numbers: '230A' },
        { name: '主颜', numbers: '230B' },
        { name: '唯思', numbers: '231A' },
        { name: '泡菜', numbers: '231-B' },
        { name: '谷彩', numbers: '232A' },
        { name: '舒适区', numbers: '232B' },
        { name: '麦士米尼', numbers: '233' },
        { name: '佳思博', numbers: '235/236' },
        { name: '艾米', numbers: '237A' },
        { name: '简新', numbers: '237B' },
        { name: '梦芭萝', numbers: '238' },
        { name: 'C.NC', numbers: '239A' },
        { name: 'xoxo', numbers: '239B' },
        { name: '美丽美丽', numbers: '240A' },
        { name: 'UGT', numbers: '240B' },
        { name: 'KC', numbers: '241A' },
        { name: 'Karma', numbers: '241B' },
        { name: '雪中画', numbers: '242A' },
        { name: '迪奥马克', numbers: '242B' },
        { name: '佳引', numbers: '243A' },
        { name: '那火', numbers: '243B' },
        { name: '妙妞', numbers: '245A' },
        { name: 'CC欧货', numbers: '245B' },
        { name: '言社', numbers: '246' },
        { name: '所靓', numbers: '247' },
        { name: '宝歌丽娅', numbers: '248/249' },
        { name: '五洲羊', numbers: '250/251' }
      ]
}
const floor3 = {
    data: [
        { name: '船皇', numbers: '301' },
        { name: '浅奈香', numbers: '302' },
        { name: '淑社', numbers: '303' },
        { name: '爱秀街区', numbers: '305-A' },
        { name: '雪纽', numbers: '305-B' },
        { name: '荔枝', numbers: '306A' },
        { name: '薇弗妮', numbers: '306B' },
        { name: '浅爱', numbers: '307' },
        { name: 'AQ', numbers: '308' },
        { name: 'DMK', numbers: '309A' },
        { name: '意林', numbers: '309B' },
        { name: '凹金', numbers: '310' },
        { name: 'queenlili', numbers: '311A' },
        { name: '花雨伞', numbers: '311B' },
        { name: '宝蓝薇', numbers: '312' },
        { name: '貂行天下', numbers: '313' },
        { name: '犀牧羊', numbers: '315A' },
        { name: '酋沫', numbers: '315B' },
        { name: '浅爱', numbers: '316' },
        { name: 'YIXFENG依枫', numbers: '317' },
        { name: '吉门', numbers: '318' },
        { name: '原一', numbers: '319A' },
        { name: 'BALALA', numbers: '319B' },
        { name: 'CINQSPET', numbers: '320A' },
        { name: 'NICE栗色', numbers: '320B' },
        { name: '法姿芬', numbers: '321A' },
        { name: '韩诗度', numbers: '321B' },
        { name: '妃形', numbers: '322A' },
        { name: '纪凡蒂娜', numbers: '322B' },
        { name: '唐古拉多斯', numbers: '323' },
        { name: '堡帝鹿', numbers: '325A' },
        { name: '鸥诗麦', numbers: '325B' },
        { name: '霸绒', numbers: '326-A' },
        { name: ' 欧麓', numbers: '326-B' },
        { name: '珊珊', numbers: '327A' },
        { name: '原创时装MG', numbers: '327B' },
        { name: '浅兰朵', numbers: '328A' },
        { name: '圣菲绒', numbers: '328B' },
        { name: '纽缦姿', numbers: '329' },
        { name: '雏秋', numbers: '330' },
        { name: '自由基调', numbers: '331-A' },
        { name: '子汐', numbers: '331-B' },
        { name: '凯蒂斯', numbers: '332A' },
        { name: '留白原创', numbers: '332B' },
        { name: '莫娜', numbers: '333A' },
        { name: '佐派欧', numbers: '333B' },
        { name: '喜喜尼', numbers: '335' },
        { name: '简嘉', numbers: '336' },
        { name: 'Eleven原创', numbers: '337A' },
        { name: '季枫', numbers: '337B' },
        { name: '欧尼', numbers: '338A' },
        { name: '罗蔓格', numbers: '338B' },
        { name: '圣羽', numbers: '339A' },
        { name: '祺影', numbers: '339B' },
        { name: '初妆', numbers: '340' },
        { name: '澜扣', numbers: '340' },
        { name: '雅扣', numbers: '341-A' },
        { name: '法赛欧', numbers: '341-B' },
        { name: '存在感', numbers: '342A' },
        { name: '奢秋', numbers: '342B' },
        { name: '柒月', numbers: '343A' },
        { name: '希若妮', numbers: '343B' },
        { name: '上步', numbers: '345A' },
        { name: '糯米', numbers: '345B' },
        { name: '洛赫亿', numbers: '346' },
        { name: '引象时装', numbers: '347' },
        { name: '欧莲娜（oulianna）', numbers: '348/349' },
        { name: '惟拉妮卡', numbers: '350/351' }
      ]
}
const floor4 = {
    data: [
        { name: '老张', numbers: '401/402' },
        { name: '柚吉吉', numbers: '403A' },
        { name: '围巾印象', numbers: '403B' },
        { name: '雪蕾娅', numbers: '405/406' },
        { name: '伊吻', numbers: '407A' },
        { name: '伊魅儿', numbers: '407B' },
        { name: '柏君燕', numbers: '408A' },
        { name: '尚莹', numbers: '408B' },
        { name: 'ECKE', numbers: '409-A' },
        { name: '聚宝绒', numbers: '409-B' },
        { name: '后', numbers: '410' },
        { name: '肯尼国际', numbers: '411' },
        { name: '播撒', numbers: '412' },
        { name: '巴尼圣迪', numbers: '413' },
        { name: '艾莎瑞亚', numbers: '415A' },
        { name: '优格妮', numbers: '415B' },
        { name: '藏绒莎', numbers: '416A' },
        { name: '初九', numbers: '416B' },
        { name: '吉祥吉', numbers: '417-A' },
        { name: '沁雨潮品', numbers: '417-B' },
        { name: '雯雯', numbers: '418-A' },
        { name: '霜露', numbers: '418-B' },
        { name: '卡诺', numbers: '419A' },
        { name: 'P&C', numbers: '419B' },
        { name: '晴倩', numbers: '420A' },
        { name: '韩曦格', numbers: '420B' },
        { name: '欧卡斐', numbers: '421' },
        { name: '"貂大姐"', numbers: '422A' },
        { name: '岑依', numbers: '422B' },
        { name: '纯米拉', numbers: '423A' },
        { name: '懂妞', numbers: '423B' },
        { name: '知美惠', numbers: '425' },
        { name: 'Y·R悠然', numbers: '426A' },
        { name: '菲菲', numbers: '426B' },
        { name: '珍熙', numbers: '427A' },
        { name: '仇小姐', numbers: '427B' },
        { name: '斯逸徕', numbers: '428A' },
        { name: '第五季', numbers: '428B' },
        { name: '艾柏卡', numbers: '429' },
        { name: 'T·HS', numbers: '430' },
        { name: '吉上羊绒', numbers: '431A' },
        { name: '卡牧羊', numbers: '431B' },
        { name: '5·G衣橱', numbers: '432A' },
        { name: 'T.O+', numbers: '432' },
        { name: '张家', numbers: '433' },
        { name: '慕诚服饰', numbers: '435' },
        { name: 'AB88', numbers: '436' },
        { name: 'V F Y', numbers: '437A' },
        { name: '冯莞儿', numbers: '437B' },
        { name: '余兰衣谷', numbers: '438' },
        { name: '米洛菲', numbers: '439A' },
        { name: '进行时', numbers: '439B' },
        { name: '络绎', numbers: '440A' },
        { name: '桂圆', numbers: '440B' },
        { name: '芭比娅', numbers: '441A' },
        { name: '目颜', numbers: '441B' },
        { name: 'Mei·Z美织', numbers: '442A' },
        { name: '语街', numbers: '442B' },
        { name: '圣简裳', numbers: '443A' },
        { name: '世纪隆达', numbers: '443B' },
        { name: '漂亮本色', numbers: '445' },
        { name: '小冉', numbers: '446A' },
        { name: 'V.V', numbers: '446B' },
        { name: '宝格格', numbers: '447A' },
        { name: '漫欧', numbers: '447B' },
        { name: '于悦', numbers: '448' },
        { name: 'CMV欧韩女装工厂店', numbers: '449' },
        { name: '黄鹤', numbers: '450' },
        { name: '原色', numbers: '451' }
      ]
}
const floor5 = {
    data: [
        { name: '范西亚', numbers: '501/502' },
        { name: '绒鑫', numbers: '503' },
        { name: 'Cindy辛迪', numbers: '505' },
        { name: '进行时', numbers: '506' },
        { name: 'waiting原创时装', numbers: '507A' },
        { name: '羊纯', numbers: '507B' },
        { name: '诺琳兰', numbers: '508' },
        { name: '艾慕尔', numbers: '509' },
        { name: '文硕家', numbers: '510' },
        { name: '圣唯吉', numbers: '511A' },
        { name: '浅姿曼', numbers: '511B' },
        { name: '卡列浓', numbers: '512A' },
        { name: '恒源玫瑰', numbers: '512B' },
        { name: '卡春', numbers: '513' },
        { name: '浅爱', numbers: '515' },
        { name: '阿米', numbers: '516A' },
        { name: '暗香盈袖', numbers: '516b' },
        { name: '九通', numbers: '517A' },
        { name: '韩歌', numbers: '517B' },
        { name: '斯卡琳', numbers: '518/519A' },
        { name: '杉宝丽', numbers: '520A' },
        { name: 'Miss.Yu', numbers: '520B' },
        { name: '麻豆可可', numbers: '521A' },
        { name: '纯蓉', numbers: '521B' },
        { name: '尚兔', numbers: '522A' },
        { name: 'JP', numbers: '522B' },
        { name: '风慕原创', numbers: '523' },
        { name: '艾斯杰围巾', numbers: '525' },
        { name: '末末', numbers: '526' },
        { name: '浣纱女', numbers: '527' },
        { name: '婕歌', numbers: '528' },
        { name: '欧洋纯', numbers: '529' },
        { name: '牧绵羊', numbers: '530' },
        { name: '本拉•拉丹', numbers: '531A' },
        { name: '玲玲家', numbers: '531B' },
        { name: '洲旭', numbers: '532' },
        { name: 'LADY.M贝贝家', numbers: '533' },
        { name: '天沐', numbers: '535' },
        { name: '依铭尚', numbers: '536' },
        { name: '第一辑', numbers: '537' },
        { name: '金鸿源', numbers: '538' },
        { name: '皇后', numbers: '539A' },
        { name: 'C6C7', numbers: '539B' },
        { name: '伊利思郎', numbers: '540' },
        { name: '湫绒', numbers: '541-A' },
        { name: '一秘六', numbers: '541-B' },
        { name: 'M.9', numbers: '542' },
        { name: '雅妞', numbers: '543A' },
        { name: '秋贝儿', numbers: '543B' },
        { name: '竹芙尼', numbers: '545' },
        { name: '艺颖', numbers: '546' },
        { name: '八爷', numbers: '547' },
        { name: '简慕妮', numbers: '548' },
        { name: '伊范', numbers: '549' },
        { name: '瑶池玫瑰', numbers: '550' },
        { name: '欧诗诗', numbers: '551' }
      ]
}
const floor6 = {
    data: [
        { name: '羽堤', numbers: '601/602' },
        { name: '石车围巾/YT益堂服饰', numbers: '603' },
        { name: '恒源祥', numbers: '605' },
        { name: '埃菲儿', numbers: '606' },
        { name: '麦纳利', numbers: '607' },
        { name: '佐佐木', numbers: '608A' },
        { name: '尤范尔', numbers: '608B' },
        { name: '依喜', numbers: '609A' },
        { name: '薇卡', numbers: '609B' },
        { name: '初心', numbers: '610A' },
        { name: '杭驰', numbers: '610B' },
        { name: '原创工厂店', numbers: '611' },
        { name: '谜路', numbers: '612A' },
        { name: 'M·L茉莉', numbers: '612B' },
        { name: '雪袖', numbers: '613' },
        { name: '嫁装', numbers: '615' },
        { name: '绒之彩', numbers: '616A' },
        { name: '七七', numbers: '616B' },
        { name: '思蒂儿', numbers: '617A' },
        { name: 'V+', numbers: '617B' },
        { name: '后简', numbers: '618' },
        { name: '麦子绮丽', numbers: '619' },
        { name: 'W+', numbers: '620' },
        { name: '', numbers: '621' },
        { name: '澳卡拉', numbers: '622' },
        { name: '丹路迪奥', numbers: '623' },
        { name: 'XAF', numbers: '625/626' },
        { name: '卡姿绒', numbers: '627/628' },
        { name: '蒂芙佳人', numbers: '629' },
        { name: 'LR鹿荣', numbers: '630' },
        { name: '俞氏名门', numbers: '631' },
        { name: '菲姿雅琪', numbers: '632' },
        { name: '月华', numbers: '633' },
        { name: '我的芭丽', numbers: '635/636' },
        { name: 'CC', numbers: '637' },
        { name: 'ER.Z二主', numbers: '638' },
        { name: 'L·Z原创', numbers: '639' },
        { name: '卡姿绒（靓莲）', numbers: '640/641' },
        { name: '广蝶', numbers: '642' },
        { name: '柒贝尔', numbers: '643' },
        { name: '依恋', numbers: '645A' },
        { name: '无店名', numbers: '645B' },
        { name: 'HS韩国定制', numbers: '646' },
        { name: '多麦', numbers: '647' },
        { name: '亮貂', numbers: '648/649' },
        { name: '若文', numbers: '650' },
        { name: '叫我女王', numbers: '651' }
      ]
}
const floor7 = {
    data: [
        { name: '麦瑟', numbers: '701/702' },
        { name: 'C.P', numbers: '703' },
        { name: 'LITTLE.FAN 点范', numbers: '705' },
        { name: '赜羽家', numbers: '706/707/708' },
        { name: '名丝曼', numbers: '709' },
        { name: '影悦', numbers: '710' },
        { name: '雅绒优', numbers: '711' },
        { name: '兰非思', numbers: '712' },
        { name: '娅秋', numbers: '713' },
        { name: '鹿亚服饰', numbers: '715/716' },
        { name: 'ZOZO', numbers: '717' },
        { name: '芊绒蒂儿', numbers: '718' },
        { name: '皮尔喜璐', numbers: '719' },
        { name: '金翎雪', numbers: '720' },
        { name: '皮尔世家', numbers: '721' },
        { name: '聚衣彩', numbers: '722' },
        { name: '佐菲米亚', numbers: '723' },
        { name: '北极貂', numbers: '725/726' },
        { name: '梵玛羊绒', numbers: '727/728' },
        { name: '金牧盾', numbers: '729' },
        { name: '可奈斯', numbers: '730' },
        { name: '五洲羊', numbers: '731/732/733' },
        { name: '秋凤凰 ', numbers: '735/736/737' },
        { name: '伊谷', numbers: '738/739' },
        { name: '禾玛氏', numbers: '740' },
        { name: 'M-8', numbers: '741' },
        { name: '天使的微笑', numbers: '742' },
        { name: '欧妮裳', numbers: '743' },
        { name: '梦幻蝶影', numbers: '745' },
        { name: '好姑娘', numbers: '746/747' },
        { name: '小芳裤业', numbers: '748/749' },
        { name: '五洲洋', numbers: '750/751' }
      ]
}
const floor8 = {
    data: [
        { name: '契西卡尼', numbers: '801/802/803/805' },
        { name: '路登国际', numbers: '806' },
        { name: '琴琴服饰', numbers: '807' },
        { name: '', numbers: '808' },
        { name: '展之威', numbers: '809' },
        { name: '香港宝龙老爷车', numbers: '810' },
        { name: 'P·R·D', numbers: '811' },
        { name: '稻草羊', numbers: '812' },
        { name: '鄂伦雅格', numbers: '813' },
        { name: '唐剑', numbers: '815' },
        { name: '郏科', numbers: '816' },
        { name: '银珠', numbers: '817/818' },
        { name: '酷酷公子羊绒', numbers: '819' },
        { name: '杜嘉歌弟', numbers: '820' },
        { name: '牧萨', numbers: '821' },
        { name: '汉成服饰', numbers: '822' },
        { name: '草原羊', numbers: '823' },
        { name: '夏帝玛', numbers: '825' },
        { name: '汉维男装', numbers: '826' },
        { name: '爱琴鸟', numbers: '827' },
        { name: '百尊汇', numbers: '828' },
        { name: '华迪堡', numbers: '829' },
        { name: '明润', numbers: '830' },
        { name: '腾莱王', numbers: '831' },
        { name: '芬迪欧歌', numbers: '832' },
        { name: '泰子隆', numbers: '833' },
        { name: '安东尼', numbers: '835/836' },
        { name: '空置', numbers: '837' },
        { name: '香港老爷车（杜丘）', numbers: '838' },
        { name: '七彩方舟', numbers: '839/840' },
        { name: '诚宇', numbers: '841' },
        { name: '顿斯雨', numbers: '842' },
        { name: '瓦多鹿王', numbers: '843' },
        { name: '欧塞德斯', numbers: '845' },
        { name: '名臣马', numbers: '846' },
        { name: '戎太子', numbers: '847' },
        { name: '无名优品', numbers: '848/849' },
        { name: '博杰才子', numbers: '850/851' }
      ]
}
const floor9 = {
    data: [
        { name: '修生', numbers: '901/902/903' },
        { name: '聚绒羊', numbers: '905/906/907' },
        { name: '伊利诺王', numbers: '908' },
        { name: '宝格王子', numbers: '909' },
        { name: '亿源羊', numbers: '910' },
        { name: '名邦迪诺', numbers: '911' },
        { name: '塞外明珠', numbers: '912' },
        { name: '卡狄玛特', numbers: '913' },
        { name: '普家斯诺', numbers: '915/916' },
        { name: '古莱文', numbers: '917' },
        { name: '羊源羊', numbers: '918' },
        { name: '九鹿王', numbers: '919' },
        { name: '宝马地亚', numbers: '920' },
        { name: '意大利皮尔卡丹', numbers: '921' },
        { name: '曼哈雷', numbers: '922' },
        { name: '皮尔卡丹', numbers: '923' },
        { name: '裕源', numbers: '925' },
        { name: '唐唐世家', numbers: '926' },
        { name: '艾克澳坤', numbers: '927' },
        { name: 'amnion', numbers: '928' },
        { name: '金鹰爵士', numbers: '929/930' },
        { name: '圣家玛奇', numbers: '931' },
        { name: '艾菲狐', numbers: '932' },
        { name: '藏澳羊', numbers: '933' },
        { name: '法狄诗', numbers: '935/936' },
        { name: '华鲨', numbers: '937/938' },
        { name: '恒爱羊', numbers: '939' },
        { name: '一衫凤凰', numbers: '940' },
        { name: '发财羊', numbers: '941' },
        { name: '青藏澳群', numbers: '942' },
        { name: '汤米狐', numbers: '943' },
        { name: '拓展针织', numbers: '945' },
        { name: '威力顿金熊', numbers: '946' },
        { name: '百迪隆裤业', numbers: '947' },
        { name: '恒源祥', numbers: '948/949' },
        { name: '霸主', numbers: '950/951' }
      ]
}
const floor10 = {
    data: [
        { name: '空', numbers: '1001' },
        { name: '空', numbers: '1002' },
        { name: '空', numbers: '1003 ' },
        { name: '小平服饰', numbers: '1005 ' },
        { name: 'H·韩', numbers: '1006 ' },
        { name: '格莱美', numbers: '1007 ' },
        { name: '黛米奥DaiMiAo', numbers: '1008 ' },
        { name: '慕·倾辰', numbers: '1009 ' },
        { name: 'ACDCC原创女装', numbers: '1010 ' },
        { name: '里墨舍南', numbers: '1011 ' },
        { name: '予西', numbers: '1012 ' },
        { name: 'EV羊绒', numbers: '1013 ' },
        { name: '世贸大食堂', numbers: '1015' },
        { name: '衣玲珑', numbers: '1016' },
        { name: '737BCF潮牌', numbers: '1017' },
        { name: 'QING+', numbers: '1018' },
        { name: '斐辣妮', numbers: '1019' },
        { name: 'DIKARONG狄卡绒', numbers: '1020' },
        { name: 'RMGN时尚女装', numbers: '1021' },
        { name: '直播供货', numbers: '1022' },
        { name: '仓库', numbers: '1023' },
        { name: '空', numbers: '1025' },
        { name: '空', numbers: '1026' },
        { name: '小卖部', numbers: '小卖部' }
      ]
}

const data = [
    floor1,
    floor2,
    floor3,
    floor4,
    floor5,
    floor6,
    floor7,
    floor8,
    floor9,
    floor10,
]

export default data